name: my_project_app
description: "A project management application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.19.0  # 날짜 포맷팅
  provider: ^6.1.1  # 상태관리

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  boolean_selector: ^2.1.1
  fake_async: ^1.3.1
  leak_tracker: ^10.0.7
  leak_tracker_flutter_testing: ^3.0.8
  lints: ^3.0.0
  matcher: ^0.12.16+1
  stack_trace: ^1.12.0
  stream_channel: ^2.1.2
  test_api: ^0.7.3
  vm_service: ^14.3.0

flutter:
  uses-material-design: true 